### ISSUE TITLE
Empty sprite costumes

### ISSUE THREAD

**Issue by cvetelinandreev** [thomaswp/snap-replay#2]
When replaying or recording with a start project, the sprites' costumes are loaded but with no content. Attached is a sample project.
If the same project is imported trough File -> Import the costume get loaded.
On the lest side is the project imported trough the menu, on the right side is the playback page with loaded startup project (start.xml in the dist/folder)

![image](https://user-images.githubusercontent.com/11582890/150631846-11dc9776-e048-4a20-a091-b71ef6a0338e.png)

[start.xml.zip](https://github.com/thomaswp/snap-replay/files/7917941/start.xml.zip)

**Comment by thomaswp** [comment]
Interesting. I'd need to do some debugging to understand why that's happening, but a simple fix would be to swap the order of the two statements. It shouldn't cause any problems and it may fix things. If not, I'm guessing it's because loading a project is asynchronous. The fix shouldn't be hard, but in the meantime all `setBlockScale` does is ensure that the blocks are zoomed to the same scale it was recorded under, so for testing it shouldn't be needed. In production, though, it's important to make sure points in the reply align correctly.

**Comment by cvetelinandreev** [comment]
Thanks for explaining why do we need the block scale set.

Swapping is a good idea since it will scale and reload an empty project before it loads the one from start.xml. However this doesn't fix the issue. It loads an empty project over the one in start.xml. How can we make the setRecordScale a sync operation?

**Comment by cvetelinandreev** [comment]
This seems to be fixed after the latest commits
